const Profiles = [
  {
    name: 'Emily Chen',
    email: 'emilychen@example.com',
    degree: 'Bachelor of Engineering',
    role: 'Software Engineer',
    linkedin: 'https://www.linkedin.com/in/emilychen',
    github: 'https://github.com/emilychen',
    image: "https://images.unsplash.com/photo-1724996854069-a7d335193ee2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDEwN3x0b3dKWkZza3BHZ3x8ZW58MHx8fHx8",
  },
  {
    name: 'David Lee',
    email: 'davidlee@example.com',
    degree: 'Master of Business Administration',
    role: 'Product Manager',
    linkedin: 'https://www.linkedin.com/in/davidlee',
    github: 'https://github.com/davidlee',
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTplvqhrIjQdARqXEBd1dBwsQTvsmBs4PFpIObYP2PveM9JlOTu"
  },
  {
    name: 'Sophia Patel',
    email: 'sophiapatel@example.com',
    degree: 'Bachelor of Arts',
    role: 'Graphic Designer',
    linkedin: 'https://www.linkedin.com/in/sophiapatel',
    github: 'https://github.com/sophiapatel',
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi4CyBUYcfa_9iioLW2LeBMh8jCyTtJi-pDQ&s"
  },
  {
    name: 'Jackson Brown',
    email: 'jacksonbrown@example.com',
    degree: 'Bachelor of Science',
    role: 'Data Analyst',
    linkedin: 'https://www.linkedin.com/in/jacksonbrown',
    github: 'https://github.com/jacksonbrown',
    image: "https://plus.unsplash.com/premium_photo-1683146516016-a5a9680f3b9d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDEwMnx0b3dKWkZza3BHZ3x8ZW58MHx8fHx8",
  },
  {
    name: 'Ava Wong',
    email: 'avawong@example.com',
    degree: 'Master of Science',
    role: 'Research Scientist',
    linkedin: 'https://www.linkedin.com/in/avawong',
    github: 'https://github.com/avawong',
    image: "https://images.unsplash.com/photo-1721417264655-2ccbf19152c6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDk0fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Ethan Kim',
    email: 'ethankim@example.com',
    degree: 'Bachelor of Fine Arts',
    role: 'UI/UX Designer',
    linkedin: 'https://www.linkedin.com/in/ethankim',
    github: 'https://github.com/ethankim',
    image: "https://plus.unsplash.com/premium_photo-1671641797308-26be77d80a2a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDk2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Lily Tran',
    email: 'lilytran@example.com',
    degree: 'Bachelor of Commerce',
    role: 'Marketing Manager',
    linkedin: 'https://www.linkedin.com/in/lilytran',
    github: 'https://github.com/lilytran',
    image: "https://images.unsplash.com/photo-1725179317686-257d18f61335?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDg2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Noah White',
    email: 'noahwhite@example.com',
    degree: 'Master of Engineering',
    role: 'DevOps Engineer',
    linkedin: 'https://www.linkedin.com/in/noahwhite',
    github: 'https://github.com/noahwhite',
    image: "https://images.unsplash.com/photo-1717558652298-c91a6ed53c5c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDczfHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Julia Hall',
    email: 'juliahall@example.com',
    degree: 'Bachelor of Science',
    role: 'Biologist',
    linkedin: 'https://www.linkedin.com/in/juliahall',
    github: 'https://github.com/juliahall',
    image: "https://plus.unsplash.com/premium_photo-1671656349322-41de944d259b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDY2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Logan Brooks',
    email: 'loganbrooks@example.com',
    degree: 'Bachelor of Arts',
    role: 'Writer',
    linkedin: 'https://www.linkedin.com/in/loganbrooks',
    github: 'https://github.com/loganbrooks',
    image: "https://plus.unsplash.com/premium_photo-1724835760606-0b40fe69f7df?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDYwfHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Abigail Martin',
    email: 'abigailmartin@example.com',
    degree: 'Master of Public Health',
    role: 'Epidemiologist',
    linkedin: 'https://www.linkedin.com/in/abigailmartin',
    github: 'https://github.com/abigailmartin',
    image: "https://images.unsplash.com/photo-1656313815939-6373a497bbf2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDYyfHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Alexander Gray',
    email: 'alexandergray@example.com',
    degree: 'Bachelor of Science',
    role: 'Chemist',
    linkedin: 'https://www.linkedin.com/in/alexandergray',
    github: 'https://github.com/alexandergray',
    image: "https://images.unsplash.com/photo-1712068944618-21bbd010c8ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDQ4fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Mia Sanchez',
    email: 'miasanchez@example.com',
    degree: 'Bachelor of Fine Arts',
    role: 'Artist',
    linkedin: 'https://www.linkedin.com/in/miasanchez',
    github: 'https://github.com/miasanchez',
    image: "https://images.unsplash.com/photo-1617138278033-ac7e498321da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDM5fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Daniel Davis',
    email: 'danieldavis@example.com',
    degree: 'Bachelor of Commerce',
    role: 'Accountant',
    linkedin: 'https://www.linkedin.com/in/danieldavis',
    github: 'https://github.com/danieldavis',
    image: "https://images.unsplash.com/photo-1613552464822-ba40bfb5f9a7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDQyfHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'John Doe',
    email: 'johndoe@example.com',
    degree: 'Bachelor of Science',
    role: 'Full Stack Developer',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    github: 'https://github.com/johndoe',
    image: "https://images.unsplash.com/photo-1725695788329-1a609af281f1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDM4fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    degree: 'Master of Arts',
    role: 'Data Scientist',
    linkedin: 'https://www.linkedin.com/in/janesmith',
    github: 'https://github.com/janesmith',
    image: "https://plus.unsplash.com/premium_photo-1724873638050-6643b159fd5e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDM3fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
    name: 'Michael Lee',
    email: 'michaellee@example.com',
    degree: 'Bachelor of Engineering',
    role: 'Software Engineer',
    linkedin: 'https://www.linkedin.com/in/michaellee',
    github: 'https://github.com/michaellee',
    image: "https://plus.unsplash.com/premium_photo-1664036154110-0875f12fa2f9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D",
  },
  {
      name: "Emily Carter",
      email: "emilyc234@marketingmail.com",
      degree: "Bachelor of Business Administration in Marketing",
      role: "Marketing Specialist",
      linkedin: "https://www.linkedin.com/in/emilycartermarketing",
      github: "https://github.com/emilyc234",
      image: "https://images.unsplash.com/photo-1612299273045-362a39972259?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDIzfHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D"
     },
    {
      name: "Alex Turner",
      email: "alex.turner@techhub.com",
      degree: "Master of Science in Computer Science",
      role: "Software Engineer",
      linkedin: "https://www.linkedin.com/in/alex-turner-softwareengineer",
      github: "https://github.com/alex-turner-dev",
      image: "https://images.unsplash.com/photo-1725759908147-9a26b5bd4581?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDM0fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D"
    },
    {
        name: "Ravi Teli",
        email: "alex.turner@techhub.com",
        degree: "BCA",
        role: "Software Engineer",
        linkedin: "https://www.linkedin.com/in/alex-turner-softwareengineer",
        github: "https://github.com/alex-turner-dev",
        image: "https://images.unsplash.com/photo-1725994390784-1ab5232a387d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D"
      },
];
  export default Profiles;