const Profiles = [
  {
    name: 'Emily Chen',
    email: 'emilychen@example.com',
    degree: 'Bachelor of Engineering',
    role: 'Software Engineer',
    linkedin: '//www.linkedin.com/in/emilychen',
    github: '//github.com/emilychen',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'David Lee',
    email: 'davidlee@example.com',
    degree: 'Master of Business Administration',
    role: 'Product Manager',
    linkedin: '//www.linkedin.com/in/davidlee',
    github: '//github.com/davidlee',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Sophia Patel',
    email: 'sophiapatel@example.com',
    degree: 'Bachelor of Arts',
    role: 'Graphic Designer',
    linkedin: '//www.linkedin.com/in/sophiapatel',
    github: '//github.com/sophiapatel',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Jackson Brown',
    email: 'jacksonbrown@example.com',
    degree: 'Bachelor of Science',
    role: 'Data Analyst',
    linkedin: '//www.linkedin.com/in/jacksonbrown',
    github: '//github.com/jacksonbrown',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Ava Wong',
    email: 'avawong@example.com',
    degree: 'Master of Science',
    role: 'Research Scientist',
    linkedin: '//www.linkedin.com/in/avawong',
    github: '//github.com/avawong',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Ethan Kim',
    email: 'ethankim@example.com',
    degree: 'Bachelor of Fine Arts',
    role: 'UI/UX Designer',
    linkedin: '//www.linkedin.com/in/ethankim',
    github: '//github.com/ethankim',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Lily Tran',
    email: 'lilytran@example.com',
    degree: 'Bachelor of Commerce',
    role: 'Marketing Manager',
    linkedin: '//www.linkedin.com/in/lilytran',
    github: '//github.com/lilytran',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Noah White',
    email: 'noahwhite@example.com',
    degree: 'Master of Engineering',
    role: 'DevOps Engineer',
    linkedin: '//www.linkedin.com/in/noahwhite',
    github: '//github.com/noahwhite',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Julia Hall',
    email: 'juliahall@example.com',
    degree: 'Bachelor of Science',
    role: 'Biologist',
    linkedin: '//www.linkedin.com/in/juliahall',
    github: '//github.com/juliahall',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Logan Brooks',
    email: 'loganbrooks@example.com',
    degree: 'Bachelor of Arts',
    role: 'Writer',
    linkedin: '//www.linkedin.com/in/loganbrooks',
    github: '//github.com/loganbrooks',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Abigail Martin',
    email: 'abigailmartin@example.com',
    degree: 'Master of Public Health',
    role: 'Epidemiologist',
    linkedin: '//www.linkedin.com/in/abigailmartin',
    github: '//github.com/abigailmartin',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Alexander Gray',
    email: 'alexandergray@example.com',
    degree: 'Bachelor of Science',
    role: 'Chemist',
    linkedin: '//www.linkedin.com/in/alexandergray',
    github: '//github.com/alexandergray',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Mia Sanchez',
    email: 'miasanchez@example.com',
    degree: 'Bachelor of Fine Arts',
    role: 'Artist',
    linkedin: '//www.linkedin.com/in/miasanchez',
    github: '//github.com/miasanchez',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Daniel Davis',
    email: 'danieldavis@example.com',
    degree: 'Bachelor of Commerce',
    role: 'Accountant',
    linkedin: '//www.linkedin.com/in/danieldavis',
    github: '//github.com/danieldavis',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'John Doe',
    email: 'johndoe@example.com',
    degree: 'Bachelor of Science',
    role: 'Full Stack Developer',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    github: 'https://github.com/johndoe',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    degree: 'Master of Arts',
    role: 'Data Scientist',
    linkedin: 'https://www.linkedin.com/in/janesmith',
    github: 'https://github.com/janesmith',
    image: "https://thispersondoesnotexist.com",
  },
  {
    name: 'Michael Lee',
    email: 'michaellee@example.com',
    degree: 'Bachelor of Engineering',
    role: 'Software Engineer',
    linkedin: 'https://www.linkedin.com/in/michaellee',
    github: 'https://github.com/michaellee',
    image: "https://thispersondoesnotexist.com",
  },
  {
      name: "Emily Carter",
      email: "emilyc234@marketingmail.com",
      degree: "Bachelor of Business Administration in Marketing",
      role: "Marketing Specialist",
      linkedin: "https://www.linkedin.com/in/emilycartermarketing",
      github: "https://github.com/emilyc234",
      image: "https://thispersondoesnotexist.com"
    },
    {
      name: "Alex Turner",
      email: "alex.turner@techhub.com",
      degree: "Master of Science in Computer Science",
      role: "Software Engineer",
      linkedin: "https://www.linkedin.com/in/alex-turner-softwareengineer",
      github: "https://github.com/alex-turner-dev",
      image: "https://thispersondoesnotexist.com"
    },
    {
        name: "Ravi Teli",
        email: "alex.turner@techhub.com",
        degree: "BCA",
        role: "Software Engineer",
        linkedin: "https://www.linkedin.com/in/alex-turner-softwareengineer",
        github: "https://github.com/alex-turner-dev",
        image: "https://thispersondoesnotexist.com"
      },
];
  export default Profiles;